apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-vishwa-rs
  labels:
    app: test-vishwa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-vishwa
  template:
    metadata:
      labels:
        app: test-vishwa
    spec:
      containers:
      - name: test-vishwa-app
        image: 0783985429/test-vishwa:latest
